### ISSUE TITLE
lis-autocontent: Read timed out error

### ISSUE THREAD

**Issue by weihuang12** [legumeinfo/jekyll-legumeinfo#128]
When I ran "make jbrowse" on jekyll-soybase lis-autocontent branch, I encountered the following errors:
See detailed message:

Traceback (most recent call last):
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/urllib3/response.py", line 441, in _error_catcher
    yield
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/urllib3/response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/requests/models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/urllib3/response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/urllib3/response.py", line 544, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/urllib3/response.py", line 446, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.legumeinfo.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/lis-autocontent", line 8, in <module>
    sys.exit(cli_entry_point())
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/lis_autocontent.py", line 19, in cli_entry_point
    cli()  # invoke cli
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/lis_cli.py", line 123, in populate_jbrowse2
    parser.parse_collections(taxa_list)  # parse_collections
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/process_collections.py", line 549, in parse_collections
    self.process_taxon(taxon)  # process taxon object
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/process_collections.py", line 527, in process_taxon
    self.process_species(
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/process_collections.py", line 440, in process_species
    self.add_collections(collection_type, genus, species)
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/process_collections.py", line 329, in add_collections
    protein_response = self.get_remote(protein_url)
  File "/Users/weihuang/Project/jekyll-soybase/venv/bin/process_collections.py", line 65, in get_remote
    response = requests.get(url, timeout=5)  # get remote object
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/requests/sessions.py", line 687, in send
    r.content
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/requests/models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/weihuang/Project/jekyll-soybase/venv/lib/python3.9/site-packages/requests/models.py", line 767, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data.legumeinfo.org', port=443): Read timed out.
make: *** [jbrowse] Error 1

**Comment by weihuang12** [comment]
adding log_level debug
```
02-16 16:21|urllib3.connectionpool|[DEBUG]: https://data.legumeinfo.org:443 "GET /Glycine/max/annotations/58-161.gnm1.ann1.HJ1K/glyma.58-161.gnm1.ann1.HJ1K.protein_primary.faa.gz HTTP/1.1" 200 11459314
02-16 16:22|urllib3.connectionpool|[DEBUG]: Starting new HTTPS connection (1): data.legumeinfo.org:443
02-16 16:22|urllib3.connectionpool|[DEBUG]: https://data.legumeinfo.org:443 "GET /Glycine/max/annotations/58-161.gnm1.ann1.HJ1K/glyma.58-161.gnm1.ann1.HJ1K.protein.faa.gz HTTP/1.1" 200 12221474
```
